---
language: ruby


arch: 
    - amd64
    - arm64
rvm:
- 2.5.8
- 2.6.6
cache: bundler
env:
  global:
  - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
  - RUBY_GC_HEAP_INIT_SLOTS=600000
  - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
  - PARALLEL_TEST_PROCESSORS=2
  matrix:
  - TEST_SUITE=vmdb PARALLEL=true
  - TEST_SUITE=brakeman
matrix:
  fast_finish: true
addons:
  postgresql: '11'
before_install:
- source ${TRAVIS_BUILD_DIR}/tools/ci/before_install.sh
- sudo apt-get install libpq-dev libcurl4-openssl-dev

before_script:
- bundle exec rake test:$TEST_SUITE:setup
script:
- bundle exec rake test:$TEST_SUITE
after_failure:
- source ${TRAVIS_BUILD_DIR}/tools/ci/after_failure.sh
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7af45001fe6b7a4039f2
    on_success: change
    on_failure: always
    on_start: never
